### ISSUE TITLE
Extension composer error

### ISSUE THREAD

**Issue by ItsEcholot** [mablanco/docker-bolt-cms#1]
The following composer error appears on installing the extension Translate (https://github.com/BoltTranslate/Translate):

```
Failed to execute git clone --no-checkout 'git@github.com:BoltTranslate/bolt-translate.git'
'/var/www/html/extensions/vendor/animal/translate' && cd '/var/www/html/extensions/vendor/animal/translate' && git remote add composer 'git@github.com:BoltTranslate/bolt-translate.git' && git fetch composer && git remote set-url origin 'git@github.com:BoltTranslate/bolt-translate.git' && git remote set-url composer 'git@github.com:BoltTranslate/bolt-translate.git'

Cloning into '/var/www/html/extensions/vendor/animal/translate'...
Could not create directory '/var/www/.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Seems like there is a problem with the host verification, and probably the permissions on the .ssh directory.

**Comment by mablanco** [comment]
The image does not take into account the possibility of using SSH as a client, so that's probably the origin of this issue. I'll have a closer look in short time and come back with a solution.

Thanks for the report.

**Comment by ItsEcholot** [comment]
Thanks for the quick response.

On further examination it seems that there is also a problem with the extension itself, as an incorrect clone url is supplied, (should be `BoltTranslate/translate.git`).
In any case I think the above report still applies to this image if ssh cloning should be supported.

**Comment by mablanco** [comment]
I've done several tests and I fear that this issue is beyond the scope of this Docker image. I've seen that Bolt is using SSH to clone the extensions repos in GitHub, comething that won't work (AFAIK) if you don't already have an account there with an uploaded  public key.

Github's recommended protocol for cloning is HTTPS, so I think this is Bolt's fault. ¿Do you know if it's possible to tell Bolt to use HTTPS instead of SSH?

**Comment by ItsEcholot** [comment]
I think you're right... Didn't think that a public key was needed for ssh cloning but that certainly makes sense. So I agree that this is Bolt's fault but I also don't know of a way to tell it to use https instead.
This whole ordeal has made me rethink using Bolt in my projects to be honest...

In any case thanks for your help and I think we can close this issue.

**Comment by mablanco** [comment]
Remember that my image is based in Bolt 3. Maybe this is already solved in Bolt 4, which uses a completely different installation process. I'd like to dockerize it sooner or later.
